### PR TITLE
Add warning when tagName is empty and data-test-* attributes are used

### LINKED ISSUE #51: test-data-* does not work when "tagName: ''" inside a component
Unfortunately the automatic attribute binding of `data-test-*` does not work when `tagName=''` in a component such as [ember-power-select](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select.js)

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves #51 

/cc @jackmatt2

### CODE REVIEW

**Comment by Turbo87** [comment]
@marcoow done

**Comment by mhluska** [comment]
This is a strange warning to force on the user because the user may be manually passing the `data-test-id` down to child elements/components. Shouldn't there be a way to opt out?

**Comment by Turbo87** [comment]
Good point. I'm open to suggestions :)

**Comment by mhluska** [comment]
Is there any way to check usage of the attribute in direct child elements/components? If not, then perhaps a environment.js config option to disable this warning?

**Comment by marcoow** [comment]
Hm, I think we should actually show the warning but **also** bind the `data-test-*` attributes as that's what a warning should be - telling the developer that what they're doing is likely wrong but not necessarily preventing anything actively?

**Comment by Turbo87** [comment]
@marcoow we can't use `attributeBindings` on `tagName: ''` components because there is no tag to bind them to...

**Comment by marcoow** [comment]
🤦‍♂️

**Pull request merged**
