### PR TITLE
use consistent headers style in README

### PR DESCRIPTION
**Pull request by marcoow**

### CODE REVIEW

**Comment by Turbo87** [comment]
FWIW I tend to prefer the current style as it gives you a hint about the maximum line lengths while writing and emphasizes the section a little more when viewed in raw format

**Comment by marcoow** [comment]
Right now it's not consistent though. Also I'm not sure the `=`/`-` allows for multiple levels of headings?

**Comment by Turbo87** [comment]
How is it not consistent?

> Also I'm not sure the =/- allows for multiple levels of headings?

It allows for two levels, which is usually enough to highlight the library title and separate the main sections from each other. For everything else (subsections, subsubsections, ...) I use the `###` syntax.

**Comment by pangratz** [comment]
I would say the existing text would be enough hint on the line width. But I don't have a preference tbh. Cowardly reassigning to @Turbo87 for the last word 😛

**Comment by marcoow** [comment]
> How is it not consistent?

We currently use `#`/`##` as well as `=`/`-`.

**Comment by Turbo87** [comment]
closing due to inactivity

**Pull request closed without merging**
